package io.suboptimal.buffjson;

import com.alibaba.fastjson2.JSONWriter;
import com.google.protobuf.Message;

import io.suboptimal.buffjson.internal.ProtobufMessageWriter;

/**
 * Generated per-message-type encoder that uses typed accessors instead of
 * reflection-style {@code getField()}.
 *
 * <p>
 * Implementations are generated by the {@code buff-json-protoc-plugin} and
 * discovered at runtime via {@link BuffJsonCodecHolder} on the message class.
 * When a generated encoder is available for a message type, it is used
 * automatically — no code changes required.
 *
 * @param <T>
 *            the concrete protobuf message type
 */
public interface BuffJsonGeneratedEncoder<T extends Message> {

	/**
	 * Writes all non-default fields of the message as JSON object content (without
	 * surrounding braces). The caller is responsible for
	 * {@code startObject}/{@code endObject}.
	 *
	 * @param writer
	 *            the message writer carrying settings (typeRegistry, useGenerated)
	 *            for recursive nested message writes
	 */
	void writeFields(JSONWriter jsonWriter, T message, ProtobufMessageWriter writer);
}
