package io.suboptimal.buffjson;

import com.alibaba.fastjson2.JSONReader;
import com.google.protobuf.Message;

import io.suboptimal.buffjson.internal.FastInput;
import io.suboptimal.buffjson.internal.ProtobufMessageReader;

/**
 * Generated per-message-type decoder that uses typed setters on the Builder
 * instead of reflection-style {@code setField()}.
 *
 * <p>
 * Implementations are generated by the {@code buff-json-protoc-plugin} and
 * discovered at runtime via {@link BuffJsonCodecHolder} on the message class.
 * When a generated decoder is available for a message type, it is used
 * automatically — no code changes required.
 *
 * @param <T>
 *            the concrete protobuf message type
 */
public interface BuffJsonGeneratedDecoder<T extends Message> {

	/**
	 * Reads a JSON object and returns a built protobuf message. The caller should
	 * NOT have consumed the opening '{' — this method reads the full JSON object
	 * including braces.
	 *
	 * @param msgReader
	 *            the message reader carrying settings (typeRegistry, useGenerated)
	 *            for recursive nested message reads
	 */
	T readMessage(JSONReader reader, ProtobufMessageReader msgReader);

	/**
	 * Reads a message straight from canonical JSON bytes, or gives up by throwing
	 * {@link FastInput#bail()}. Never reports a parse error of its own: whenever
	 * the input is anything other than plain canonical proto3 JSON the caller
	 * re-runs it through {@link #readMessage}, which owns error handling. Generated
	 * decoders that predate this method inherit the default and always give up.
	 *
	 * @param in
	 *            the cursor, positioned at the message's opening brace
	 */
	default T readFast(FastInput in) {
		throw FastInput.bail();
	}
}
