package io.suboptimal.buffjson;

import com.alibaba.fastjson2.JSONReader;
import com.google.protobuf.Message;

/**
 * Generated per-message-type decoder that uses typed setters on the Builder
 * instead of reflection-style {@code setField()}.
 *
 * <p>
 * Implementations are generated by the {@code buff-fastjson-protoc-plugin} and
 * discovered at runtime via {@link java.util.ServiceLoader}. When a generated
 * decoder is available for a message type, it is used automatically — no code
 * changes required.
 *
 * @param <T>
 *            the concrete protobuf message type
 */
public interface GeneratedDecoder<T extends Message> {

	/** The fully-qualified protobuf type name (e.g., "my.package.MyMessage"). */
	String descriptorFullName();

	/**
	 * Reads a JSON object and returns a built protobuf message. The caller should
	 * NOT have consumed the opening '{' — this method reads the full JSON object
	 * including braces.
	 */
	T readMessage(JSONReader reader);
}
